#### KIVYMD APP BUILDER ####
### WRITTEN BY: @nicodotgit ###

#######################################

name: Build APP

## TRIGGERS
on:
  push:
    branches:
      - main
    paths:
      - '*.py'
      - '*.spec'
      - 'assets/*.png'
      - '.github/workflows/build.yml'

## ENVIRONMENT
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@master

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'adopt'

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y zip unzip autoconf automake m4 gettext libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential python3 python3-pip python3-setuptools python3-wheel python3-dev git
        pip install kivy https://github.com/kivymd/KivyMD/archive/master.zip materialyoucolor exceptiongroup asyncgui asynckivy Cython virtualenv setuptools wheel buildozer

    # Run buildozer
    - name: Run buildozer
      run: |
        buildozer android debug

    # Prepare artifact
    - name: Prepare artifact
      id: prepareArtifact
      run: |
        artifactUpload=`ls -t bin/*.apk | head -n1`
        artifactName="app-${{ github.sha }}-arm64_v8a"
        mv $artifactUpload bin/$artifactName.apk
        artifactUpload="bin/$artifactName.apk"
        echo "artifactUpload=$artifactUpload" >> $GITHUB_OUTPUT
        echo "artifactName=$artifactName" >> $GITHUB_OUTPUT
    
    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.prepareArtifact.outputs.artifactName }}
        path: ${{ steps.prepareArtifact.outputs.artifactUpload }}

    # Commit and push
    - name: Commit and push
      run: |
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add bin/*
        git commit -m "Add compiled APK from latest commit" -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # Upload to releases
    - name: Upload to releases
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.prepareArtifact.outputs.artifactUpload }}
        asset_name: ${{ steps.prepareArtifact.outputs.artifactName }}.apk
        tag: build-${{ github.sha }}

#################### END OF WORKFLOW ####################